# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Arash Pourhabibi
title: A computer geek, a food lover, and a traveler-wannabe
email: arash.pourhabibi@epfl.ch
phone:  +41 21 693 13 79
website: arash.pourhabibi.info

# Social links
twitter_username: ArashPourhabibi
github_username:  neo-apz
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: neo_apz
linkedin_username: arashpourhabibizarandi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is [Arash](https://en.wikipedia.org/wiki/Arash) (Persian: آرش) (aka NEO).
  I am a PhD candidate at the [School of Computer and Communication Sciences](http://ic.epfl.ch/),
  [EPFL](https://www.epfl.ch/en/home/), and a doctoral research assistant at [PARSA](http://parsa.epfl.ch)
  under supervision of [Prof. Babak Falsafi](http://parsa.epfl.ch/~falsafi/).
  I did my master’s in Software Engineering at the Department of CSE and IT of
  [Shiraz University](http://en.wikipedia.org/wiki/Shiraz_University),
  where I also received my B.Sc. in Software Engineering.

# Interests Section
# interests_title: Research Interests
interests_content: | # this will include new lines to allow paragraphs
  I am broadly interested in the field of computer systems and interdisciplinary systems-level problems found in modern,
  large-scale datacenters, from cloud services to data stores and all the way down to server systems.
  By characterizing modern datacenter applications, I look for maximizing the compute density of server systems
  and minimizing their energy footprint through specialization of various system components and better system integration.
  My current focus is on the evasion of the RPC tax in datacenters through hardware-software co-design.

cv: files/cv.pdf
cv_updated: May 2021

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /:year-:month-:day-:title/

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50
